name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: false
          bodyFile: "CHANGELOG.md"
          
